swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: Add User Transaction (Automated)
      description: Add a new user transaction generated by the bank
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token or Automated Transaction Token
          required: true
        - in: body
          name: body
          description: Add automated user transaction details
          required: true
          schema:
            $ref: "#/definitions/AutomatedUserTransactionAdd"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction added successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized (Invalid Automated Transaction Token)
        "500":
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User transactions API
      description: Attach Bearer JWT token
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
        - in: body
          name: body
          description: Get user transactions
          schema:
            $ref: "#/definitions/UserTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: Update User Transaction
      description: Update user transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user transaction details
          required: []
          schema:
            $ref: "#/definitions/UserTransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile/transaction/note:
    delete:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: Delete User Transaction Note
      description: Delete the note associated with a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Delete user transaction note
          required: true
          schema:
            $ref: "#/definitions/UserTransactionNoteDelete"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction note deleted successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserTransactions:
    type: object
    properties:
      id:
        type: string
        description: ID of transaction
      body:
        type: object
        properties:
          checking:
            type: array
            description: array for statut of transaction (pending, validate, refused.)
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: details of transaction
          amount:
            type: integer
            description: amount transaction
          balance:
            type: integer
            description: available balance
          transactionType:
            type: string
            description: type of transaction
          category:
            type: string
          notes:
            type: string
  UserTransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Updated transaction category
      notes:
        type: string
        description: Updated transaction notes
    required: []
  UserTransactionNoteDelete:
    type: object
    properties:
      transactionId:
        type: string
        description: ID of the transaction for which the note should be deleted
    required:
      - transactionId
  AutomatedUserTransactionAdd:
    type: object
    properties:
      transactionType:
        type: string
        description: Type of automated transaction (transfer, withdrawal, card payment, etc.)
      amount:
        type: integer
        description: Transaction amount
      category:
        type: string
        description: Transaction category (optional)
      notes:
        type: string
        description: Transaction notes (optional)
      source:
        type: string
        description: Source identifier (bank system)
      transactionToken:
        type: string
        description: Token for authenticating automated transaction requests
    required:
      - transactionType
      - amount
      - source
      - transactionToken
